name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Cache OpenCV
      id: opencv-cache
      uses: actions/cache@v2
      with:
        path: ./opencv-install
        key: ${{ runner.os }}-opencv-cache

    - name: Install OpenCV
      uses: rayandrews/with-opencv-action@v1
      with:  
        dir: ./opencv-install
        cached: ${{ steps.opencv-cache.outputs.cache-hit }}
        opencv-version: '4.0.0'

    - name: Setup Boost
      run: |
        sudo apt update
        sudo apt install -y libboost-all-dev

    - name: Configure CMake
      working-directory: Assignment 1
      run:
       cmake .

    - name: Build
      working-directory: Assignment 1
      run: make
